# Generated by Django 6.0.6 on 2026-06-24 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Intentos máximos')),
                ('min_score', models.PositiveIntegerField(default=80, verbose_name='Nota mínima para aprobar (%)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='Curso')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='courses.module', verbose_name='Módulo (opcional)')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Inicio del intento')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin del intento')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota obtenida')),
                ('is_passed', models.BooleanField(default=False, verbose_name='¿Aprobado?')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='progress.exam', verbose_name='Evaluación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Intento de evaluación',
                'verbose_name_plural': 'Intentos de evaluación',
                'db_table': 'intentos_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Enunciado de la pregunta')),
                ('question_type', models.CharField(choices=[('multiple', 'Opción múltiple'), ('true_false', 'Verdadero/Falso'), ('single', 'Única respuesta')], default='multiple', max_length=20, verbose_name='Tipo de pregunta')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Autor (profesor)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Banco de preguntas',
                'db_table': 'banco_preguntas',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='Texto de la opción')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='progress.questionbank', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de respuesta',
                'verbose_name_plural': 'Opciones de respuesta',
                'db_table': 'opciones_pregunta',
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Correcta?')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='progress.examattempt', verbose_name='Intento')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.questionbank', verbose_name='Pregunta')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.questionoption', verbose_name='Opción seleccionada')),
            ],
            options={
                'verbose_name': 'Respuesta de intento',
                'verbose_name_plural': 'Respuestas de intentos',
                'db_table': 'respuestas_intentos',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Código de verificación')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificados',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('total_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progreso total (%)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripciones',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('percentage', models.PositiveIntegerField(default=0, verbose_name='Porcentaje de avance')),
                ('last_video_position', models.PositiveIntegerField(default=0, verbose_name='Última posición del video (segundos)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson', verbose_name='Lección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Progreso de lección',
                'verbose_name_plural': 'Progresos de lecciones',
                'db_table': 'progreso_lecciones',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=10, verbose_name='Puntaje de la pregunta')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='progress.exam', verbose_name='Evaluación')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='progress.questionbank', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Pregunta de evaluación',
                'verbose_name_plural': 'Preguntas de evaluación',
                'db_table': 'preguntas_evaluacion',
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
