# Generated by Django 6.0.6 on 2026-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Ícono'),
        ),
    ]
