# Generated by Django 6.0.6 on 2026-06-24 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('professor', 'Profesor'), ('admin', 'Administrador')], default='student', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='usuarios',
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de sesión')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Cierre de sesión')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Acceso',
                'verbose_name_plural': 'Sesiones de Acceso',
                'db_table': 'sesiones_acceso',
            },
        ),
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(blank=True, max_length=200, verbose_name='Título profesional')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Especialidad')),
                ('biography', models.TextField(blank=True, verbose_name='Biografía')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL de LinkedIn')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Profesor',
                'verbose_name_plural': 'Perfiles de Profesores',
                'db_table': 'perfiles_profesor',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, verbose_name='Biografía')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL del avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Estudiante',
                'verbose_name_plural': 'Perfiles de Estudiantes',
                'db_table': 'perfiles_estudiante',
            },
        ),
    ]
