# Generated by Django 6.0.6 on 2026-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role_alter_user_table_accesslog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
