# Generated by Django 6.0.6 on 2026-07-06 18:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Nombre")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievements/", verbose_name="Ícono"
                    ),
                ),
                (
                    "criteria",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Criterio de desbloqueo (ej: completar 5 cursos)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro",
                "verbose_name_plural": "Logros",
                "db_table": "logros",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Nombre")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Código")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Porcentaje"), ("fixed", "Monto fijo")],
                        default="percentage",
                        max_length=20,
                        verbose_name="Tipo de descuento",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor del descuento"
                    ),
                ),
                ("max_uses", models.PositiveIntegerField(default=100, verbose_name="Usos máximos")),
                (
                    "current_uses",
                    models.PositiveIntegerField(default=0, verbose_name="Usos actuales"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fecha de expiración"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
            ],
            options={
                "verbose_name": "Cupón",
                "verbose_name_plural": "Cupones",
                "db_table": "cupones",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("content_text", models.TextField(blank=True, verbose_name="Contenido teórico")),
                ("video_url", models.URLField(blank=True, verbose_name="URL del video")),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Duración (segundos)"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Orden")),
                (
                    "completion_percentage",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Porcentaje de avance necesario para considerar la lección completada",
                        verbose_name="% para completar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lección",
                "verbose_name_plural": "Lecciones",
                "db_table": "lecciones",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Estudiante"),
                            ("professor", "Profesor"),
                            ("admin", "Administrador"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Teléfono")),
                ("biography", models.TextField(blank=True, verbose_name="Biografía")),
                ("country", models.CharField(blank=True, max_length=100, verbose_name="País")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de nacimiento"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="Avatar"
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(blank=True, max_length=200, verbose_name="Título profesional"),
                ),
                (
                    "specialty",
                    models.CharField(blank=True, max_length=200, verbose_name="Especialidad"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="URL de LinkedIn")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "ordering": ["username"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito",
                "verbose_name_plural": "Carritos",
                "db_table": "carritos",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/covers/",
                        verbose_name="Imagen de portada",
                    ),
                ),
                ("slug", models.SlugField(max_length=280, unique=True, verbose_name="Slug")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="courses.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "db_table": "cursos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de publicación"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor (profesor)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anuncio",
                "verbose_name_plural": "Anuncios",
                "db_table": "anuncios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "max_attempts",
                    models.PositiveIntegerField(default=3, verbose_name="Intentos máximos"),
                ),
                (
                    "min_score",
                    models.PositiveIntegerField(
                        default=80, verbose_name="Nota mínima para aprobar (%)"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fecha de inicio"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fecha de fin"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "db_table": "evaluaciones",
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inicio del intento"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin del intento"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Nota obtenida",
                    ),
                ),
                ("is_passed", models.BooleanField(default=False, verbose_name="¿Aprobado?")),
                (
                    "answers",
                    models.JSONField(
                        default=list,
                        help_text='Lista: [{"question_id": 1, "option_index": 0, "option_text": "...", "is_correct": true}]',
                        verbose_name="Respuestas del intento",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="courses.exam",
                        verbose_name="Evaluación",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de evaluación",
                "verbose_name_plural": "Intentos de evaluación",
                "db_table": "intentos_evaluacion",
            },
        ),
        migrations.CreateModel(
            name="ForumThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_threads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_threads",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema de foro",
                "verbose_name_plural": "Temas de foro",
                "db_table": "foros_temas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="courses.forumthread",
                        verbose_name="Hilo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de foro",
                "verbose_name_plural": "Mensajes de foro",
                "db_table": "foros_mensajes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="courses.lessoncomment",
                        verbose_name="Comentario padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario de lección",
                "verbose_name_plural": "Comentarios de lecciones",
                "db_table": "comentarios_lecciones",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                ("order", models.PositiveIntegerField(verbose_name="Orden")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "db_table": "modulos",
                "ordering": ["order"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.module",
                verbose_name="Módulo",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="courses.module",
                verbose_name="Módulo (opcional)",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Total"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagada"),
                            ("cancelled", "Cancelada"),
                            ("refunded", "Reembolsada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fecha de pago"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="courses.coupon",
                        verbose_name="Cupón aplicado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden",
                "verbose_name_plural": "Órdenes",
                "db_table": "ordenes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Enunciado de la pregunta")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple", "Opción múltiple"),
                            ("true_false", "Verdadero/Falso"),
                            ("single", "Única respuesta"),
                        ],
                        default="multiple",
                        max_length=20,
                        verbose_name="Tipo de pregunta",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text='Lista de objetos: [{"text": "...", "is_correct": true/false}]',
                        verbose_name="Opciones de respuesta",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor (profesor)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Banco de preguntas",
                "db_table": "banco_preguntas",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="resources/", verbose_name="Archivo"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("video", "Video"),
                            ("code", "Código"),
                            ("link", "Enlace"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Tipo de recurso",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "db_table": "recursos",
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Asunto")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("in_progress", "En progreso"),
                            ("resolved", "Resuelto"),
                            ("closed", "Cerrado"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "messages",
                    models.JSONField(
                        default=list,
                        help_text='Lista: [{"sender_id": 1, "sender_name": "...", "message": "...", "sent_at": "ISO"}]',
                        verbose_name="Mensajes del ticket",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket de soporte",
                "verbose_name_plural": "Tickets de soporte",
                "db_table": "tickets_soporte",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        unique=True,
                        verbose_name="Código de verificación",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de emisión"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "db_table": "certificados",
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de agregado"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="courses.cart",
                        verbose_name="Carrito",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem del carrito",
                "verbose_name_plural": "Ítems del carrito",
                "db_table": "carritos_items",
                "unique_together": {("cart", "course")},
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de inscripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "total_progress",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Progreso total (%)"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "db_table": "inscripciones",
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False, verbose_name="Completada")),
                (
                    "percentage",
                    models.PositiveIntegerField(default=0, verbose_name="Porcentaje de avance"),
                ),
                (
                    "last_video_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Última posición del video (segundos)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de lección",
                "verbose_name_plural": "Progresos de lecciones",
                "db_table": "progreso_lecciones",
                "unique_together": {("user", "lesson")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("module", "order")},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio unitario"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="courses.order",
                        verbose_name="Orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de orden",
                "verbose_name_plural": "Ítems de orden",
                "db_table": "ordenes_items",
                "unique_together": {("order", "course")},
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(default=10, verbose_name="Puntaje de la pregunta"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="courses.exam",
                        verbose_name="Evaluación",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="courses.questionbank",
                        verbose_name="Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta de evaluación",
                "verbose_name_plural": "Preguntas de evaluación",
                "db_table": "preguntas_evaluacion",
                "unique_together": {("exam", "question")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Puntuación (1-5)",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comentario")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reseña",
                "verbose_name_plural": "Reseñas",
                "db_table": "resenas",
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de obtención"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="courses.achievement",
                        verbose_name="Logro",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro de usuario",
                "verbose_name_plural": "Logros de usuarios",
                "db_table": "logros_usuarios",
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
